# Problem Set 4B
# Name:
# Collaborators:

import random


class Message(object):
    def __init__(self, input_text):
        '''
        Initializes a Message object

        input_text (string): the message's text

        a Message object has one attribute:
            the message text
        '''
        self.input_text = input_text

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''Message('{self.get_text()}')'''

    def get_text(self):
        '''
        Used to access the message text outside of the class

        Returns: (string) the message text
        '''
        return self.input_text

    def shift_char(self, char, shift):
        '''
        Used to shift a character as described in the pset handout

        char (string): the single character to shift.
                    ASCII value in the range: 32<=ord(char)<=126
        shift (int): the amount to shift char by

        Returns: (string) the shifted character with ASCII value in the range [32, 126]
        '''
        return chr((ord(char) + shift - 32) % (126 - 32 + 1) + 32)

    def apply_pad(self, pad):
        '''
        Used to calculate the ciphertext produced by applying a one time pad to the message text.
        For each character in the text at index i shift that character by
            the amount specified by pad[i]

        pad (list of ints): a list of integers used to encrypt the message text
                        len(pad) == len(the message text)

        Returns: (string) The ciphertext produced using the one time pad

        用于计算将一次性密码本应用于消息文本后生成的密文。
        对于文本中索引为 i 的每个字符，将其位移 pad[i] 指定的量

        pad (list of ints): 用于加密消息文本的整数列表
                        len(pad) == len(消息文本)

        Returns: (string) 使用一次性密码本生成的密文
        '''
        list_1 = list(self.get_text())
        str_2 = ''
        for i in range(len(list_1)):
            char_1 = self.shift_char(list_1[i], pad[i])
            str_2 += char_1
        return str_2


class PlaintextMessage(Message):
    def __init__(self, input_text, pad=None):
        '''
        Initializes a PlaintextMessage object.

        input_text (string): the message's text
        pad (list of ints OR None): the pad to encrypt the input_text or None if left empty
            if pad is not None then len(pad) == len(self.input_text)

        A PlaintextMessage object inherits from Message. It has three attributes:
            the message text
            the pad (list of integers, determined by pad
                or generated randomly using self.generate_pad() if pad is None)
            the ciphertext (string, input_text encrypted using the pad)
            
        初始化一个 PlaintextMessage 对象。

        input_text (字符串): 消息的文本
        pad (整数列表 或 None): 用于加密 input_text 的填充码 (pad)，若留空则为 None
        如果 pad 不为 None，则 len(pad) 必须等于 len(self.input_text)

        PlaintextMessage 对象继承自 Message 类。它包含三个属性：
        消息文本 (message text)
        填充码 (pad) (整数列表，由参数 pad 决定，
                   或者如果参数 pad 为 None，则通过 self.generate_pad() 随机生成)
        密文 (ciphertext) (字符串，即使用 pad 加密后的 input_text)    
        '''
        Message.__init__(self, input_text)
        if pad != None:
            pad_1 = []
            for i in range(len(pad)):
                pad_1.append(pad[i])
            self.pad = pad_1
        else:
            self.pad = self.generate_pad()
        self.ciphertext = self.apply_pad(self.pad)

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''PlaintextMessage('{self.get_text()}', {self.get_pad()})'''

    def generate_pad(self):
        '''
        Generates a one time pad which can be used to encrypt the message text.

        The pad should be generated by making a new list and for each character
            in the message chosing a random number in the range [0, 110) and
            adding that number to the list.

        Returns: (list of integers) the new one time pad
        
        生成一个可用于加密消息文本的一次性填充码 (one time pad)。

        该填充码的生成方式为：创建一个新列表，针对消息中的每一个字符，
            在 [0, 110) 范围内选择一个随机数，并将该数字添加到列表中。

        返回: (整数列表) 新的一次性填充码
        '''
        list_1 = []
        for i in range(len(self.input_text)):
            list_1.append(random.randint(0, 109))
        return list_1

    def get_pad(self):
        '''
        Used to safely access your one time pad outside of the class

        Returns: (list of integers) a COPY of your pad
        '''
        list_1 = []
        for i in range(len(self.pad)):
            list_1.append(self.pad[i])
        return list_1
        
    def get_ciphertext(self):
        '''
        Used to access the ciphertext produced by applying pad to the message text

        Returns: (string) the ciphertext
        '''
        return self.apply_pad(self.get_pad())

    def change_pad(self, new_pad):
        '''
        Changes the pad used to encrypt the message text and updates any other
        attributes that are determined by the pad.

        new_pad (list of ints): the new one time pad that should be associated with this message.
            len(new_pad) == len(the message text)

        Returns: nothing
        '''
        self.pad = new_pad


class EncryptedMessage(Message):
    def __init__(self, input_text):
        '''
        Initializes an EncryptedMessage object

        input_text (string): the ciphertext of the message

        an EncryptedMessage object inherits from Message. It has one attribute:
            the message text (ciphertext)
            
        初始化一个 EncryptedMessage 对象

        input_text (字符串): 消息的密文

        EncryptedMessage 对象继承自 Message 类。它有一个属性：
            消息文本 (密文)    
        '''
        Message.__init__(self, input_text)

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''EncryptedMessage('{self.get_text()}')'''

    def decrypt_message(self, pad):
        '''
        Decrypts the message text that was encrypted with pad as described in the writeup

        pad (list of ints): the new one time pad used to encrypt the message.
            len(pad) == len(the message text)

        Returns: (PlaintextMessage) the decrypted message (containing the pad)
        
        根据作业文档的描述，解密使用 pad 加密的消息文本

        pad (整数列表): 用于加密消息的新的一次性填充码 (one time pad)。
            len(pad) 必须等于 len(消息文本)

        返回: (PlaintextMessage) 解密后的消息对象 (包含该 pad)
        '''
        pad_1= [-x for x in pad]
        return PlaintextMessage(self.apply_pad(pad_1), pad)

